[project]
name = "HCSE"
version = "0.1.0"
description = "The hackclub stock exchange!"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flask>=3.1.1",
    "numpy>=2.2.6",
    "surrealdb>=1.0.4",
]
